### ISSUE TITLE
https://docs.opensds.io/features/ -- updates needed

### ISSUE THREAD

**Issue by skdwriting** [sodafoundation/documentation#31]
/kind new-documentation

**What happened**:
Document Name: https://docs.opensds.io/features/ - all features
Document Path / Location: https://docs.opensds.io/features/
Please update all the features related documentations in this page. (Many missing like multicloud ....- check all and update)- the feature architecture documents are not accessible from the docs page as well

**Comment by Kgkunal** [comment]
Hello @anvithks  @skdwriting  @kumarashit ,

I'm interested in working on this documentation issue. I've noticed that the page URL `https://docs.opensds.io/features/` is currently returning a 404 error, which suggests that there might be issues with the accessibility of the documentation.

Could you please provide more information about the specific features that need to be documented or updated on this page? It would be helpful to understand what's missing or incomplete so that I can provide comprehensive documentation.

Additionally, if there are any guidelines or requirements for this task, please let me know. I'm eager to contribute and ensure that the documentation is accurate and accessible to users.
![image_2023-09-16_193324132](https://github.com/sodafoundation/documentation/assets/76809868/d0081529-6cb9-41d8-aef9-73130162c0c9)

**Comment by anvithks** [comment]
@Kgkunal This is a stale issue from 2020. The documentation has been updated and this page no longer exists. I will be closing this issue. Thanks for bringing it to our notice.

**Comment by Kgkunal** [comment]
Thank you for your prompt response and for addressing the status of this issue. I appreciate the clarification that the documentation has been updated, and this page no longer exists.

If there are any other documentation tasks or areas where I can contribute, please do let me know. I'm eager to help ensure the project's documentation remains accurate and accessible.

Once again, thank you for your time and assistance.
